# Generated by Django 4.2 on 2023-04-17 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва класу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Виводити на сторінці')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Клас',
                'verbose_name_plural': 'Класи',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва предмету')),
                ('order', models.IntegerField(default=1, verbose_name='Порядок виводу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Виводити на сторінці')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
            },
        ),
        migrations.CreateModel(
            name='GradeSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', editable=False, max_length=150, unique=True, verbose_name='Клас-Предмет (заповнюється автоматично)')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('additional_id', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=10, unique=True, verbose_name='Додатковий ID')),
                ('slug_grade', models.SlugField(blank=True, default='', editable=False, max_length=255, verbose_name='slug класу (заповнюється автоматично)')),
                ('slug_subject', models.SlugField(blank=True, default='', editable=False, max_length=255, verbose_name='slug предмету (заповнюється автоматично)')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.grade', verbose_name='Клас')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Зв"язок Клас - Предмет',
                'verbose_name_plural': 'Зв"язки Клас - Предмет',
            },
        ),
    ]
